<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Manifest file.
    |--------------------------------------------------------------------------
    |
    | Manifest json file, generated by webpack-assets plugin. It's path
    | is relative to disk directory. See `disk` parameter.
    |
    */
    'file'         => 'assets/manifest.json',

    /*
    |----------------------------------------------------------------------
    | Throw loading exception.
    |----------------------------------------------------------------------
    |
    | When first call of webpack package call occurred it loads manifest
    | file. If no file was created, by default, it will throw exception.
    | Set this to false if you want to prevent exception to be thrown.
    |
    */
    'fail_on_load' => false,

    /*
    |----------------------------------------------------------------------
    | Filesystem disk.
    |----------------------------------------------------------------------
    |
    | To be able to retrieve paths of files from any disk just set here
    | which disk you want to use for manifest file and all assets.
    | see `config/filesystems` for available disks list.
    |
    */
    'disk' => 'public',
];